### ISSUE TITLE
Unable to see if there are updates or not

### ISSUE THREAD

**Issue by FunkeyMonkey** [chirmstream/unraid-templates#3]
Seafile shows not available under version for some reason. Have tried force update but still won't show up-to-date.

![image](https://github.com/user-attachments/assets/766b03fa-f8c5-4923-a4fe-c8fd3903f117)

**Comment by Gusfit2** [comment]
Oh I've just posted a new issue about this before reading yours:

https://github.com/chirmstream/unraid-templates/issues/4#issue-2573824022

Update the template's repository to `seafileltd/seafile-mc:11.0-latest`

**Comment by elmuziko** [comment]
Worse than that, Unraid plugin "Fix Common Problems" is also warning:
`seafile (seafileltd/seafile-mc:latest) has the following comments: No longer available on dockerHub Additionally, this application has been blacklisted from Community Applications for that reason.`
Have applied manual fix, but this could trip people up.

**Comment by chirmstream** [comment]
Two reasons why I haven't fixed this yet, I'd like like to hear some of other people's thoughts on this.  
1. I've been busy, ha
2. I have had issues in the past when I use using Nextcloud and updating before I was ready.  What happened with me was there was a Nextcloud update, say version C, that required you to be on version B before updating.  The problem was, I hadn't updated for a while and was still on version A.  I pulled down the new docker image without reading the changes, and Nextcloud wouldn't start because I skipped too many versions.  Pulling down my previous docker image wouldn't help, it was too late and it wouldn't run without manually restoring all the files, settings, etc.  In the meantime my household can't use it because it broke when I tried running the new docker image.

**Comment by elmuziko** [comment]
Personally, I'm just grateful to have SeaFile consistently working. I probably wouldn't have noticed the issue myself had I not had a power failure and UnRAID taken me straight to "Fix Common Problems" with red errors.

There's always going to be issues beyond your control, set-ups that aren't updated or using an unsupported/outdated DB to host. You can only do so much. 

Whatever side the coin lands on, my personal thanks for your work on this project.

**Comment by FunkeyMonkey** [comment]
> Worse than that, Unraid plugin "Fix Common Problems" is also warning: `seafile (seafileltd/seafile-mc:latest) has the following comments: No longer available on dockerHub Additionally, this application has been blacklisted from Community Applications for that reason.` Have applied manual fix, but this could trip people up.

What manual fix did you apply?

**Comment by elmuziko** [comment]
> 
> What manual fix did you apply? Are you talking about the :latest thing? My seafile shows up-to-date now, but I do still have the blacklisted message

My repo is :
seafileltd/seafile-mc:11.0-latest

That was the only change I've made. No issues on my Fix Common Problems since.

**Comment by FunkeyMonkey** [comment]
> > What manual fix did you apply? Are you talking about the :latest thing? My seafile shows up-to-date now, but I do still have the blacklisted message
> 
> My repo is : seafileltd/seafile-mc:11.0-latest
> 
> That was the only change I've made. No issues on my Fix Common Problems since.

Gotcha, I did update the repo setting and now it shows up to date, but I've been getting a new issue with the apps section. I get a notification in action centre anytime i go to apps with the following about Seafile.

![image](https://github.com/user-attachments/assets/f0dba3eb-da5b-4e50-af1f-63cceb3f8c31)

**Comment by chirmstream** [comment]
Do you think it's better to have different templates for each Seafile version, or to setup different branches on one template for each version.

### Option 1
![image](https://github.com/user-attachments/assets/7ee80dd7-98e4-45e0-ae92-b23e62dfe992)
### Option 2
![image](https://github.com/user-attachments/assets/ab8ea953-dff9-49ff-80a1-913be4aa408d)

I haven't setup a template with multiple branches yet, but if someone wants to try, here is the [documentation ](https://forums.unraid.net/topic/38619-docker-template-xml-schema/page/2/#comment-491269)I found for it.

**Comment by chirmstream** [comment]
All,

I've added two new templates for seafile 10 and seafile 11 with the fixed docker registry. I was able to successfully do a fresh install and update to v11 on my unraid sever. I've closed this issue as it should be resolved now. 

Thank you

**Comment by FunkeyMonkey** [comment]
Thanks for that! On a side note, is there anyway to fix the blacklist of the app or is that just expected from using a custom template to install it?

**Comment by chirmstream** [comment]
I think after a few days it will update and should no longer be blacklisted.
