### ISSUE TITLE
Seafile Unraid - "seafileltd/seafile-mc:latest not found: manifest unknown"

### ISSUE THREAD

**Issue by Gusfit2** [chirmstream/unraid-templates#4]
The Seafile Unraid template no longer points to the latest release, I think somewhere along the way their `:latest` tag was updated to include the major version number.

It needs to be updated from

`seafileltd/seafile-mc` 

to 

`seafileltd/seafile-mc:11.0-latest`

**Comment by chirmstream** [comment]
Closing this issue since we already have #3, which is covering the same problem.
