### ISSUE TITLE
Seafile no longer listed on Unraid app store

### ISSUE THREAD

**Issue by Gusfit1** [chirmstream/unraid-templates#6]
Sorry to bug you again, it seems that your Seafile xml is no longer listed on the app store since the recent updates.

**Comment by chirmstream** [comment]
I'm working on it.  Latest commit 0ce388484ad36a2a96921fd73a473730c2fd03f4 should have fixed everything.

**Comment by chirmstream** [comment]
Closing this issue because shows up in the app store for me now.
